// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zshvzaqxtbtwvcchpkeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzaHZ6YXF4dGJ0d3ZjY2hwa2ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2Mzg5NzQsImV4cCI6MjA3MTIxNDk3NH0.WONNoa3zUtA2zAGLB_fRY232I5BSsronSXw8jsnAL-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});